"use client"

import { jsPDF } from "jspdf"

interface PrepPackSection {
  name: string
  marks: number
  questions: Array<{
    id: string
    text: string
    marks?: number
    answer?: string
    type: string
  }>
}

interface PrepPackContent {
  sections: PrepPackSection[]
  formulas?: string[]
  tips?: string[]
  summary?: string
}

interface PrepPackData {
  title: string
  subject: string
  totalMarks: number
  content: PrepPackContent
  createdAt: string
}

export function generatePrepPackPDF(data: PrepPackData): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  let yPos = margin

  const addWatermark = () => {
    doc.setTextColor(220, 220, 220)
    doc.setFontSize(40)
    doc.text("ExamEase", pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 45,
    })
    doc.setTextColor(0, 0, 0)
  }

  const checkNewPage = (requiredSpace: number = 30) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      doc.addPage()
      yPos = margin
      addWatermark()
    }
  }

  // Title Page
  addWatermark()
  
  doc.setFontSize(24)
  doc.setFont("helvetica", "bold")
  doc.text(data.title, pageWidth / 2, 50, { align: "center" })

  doc.setFontSize(14)
  doc.setFont("helvetica", "normal")
  doc.text(`Subject: ${data.subject}`, pageWidth / 2, 70, { align: "center" })
  doc.text(`Total Marks: ${data.totalMarks}`, pageWidth / 2, 80, { align: "center" })

  doc.setFontSize(10)
  doc.text(`Generated: ${new Date(data.createdAt).toLocaleDateString()}`, pageWidth / 2, 95, {
    align: "center",
  })

  doc.setFontSize(12)
  doc.text("Generated by ExamEase - Smart Study & Exam Companion", pageWidth / 2, 110, {
    align: "center",
  })

  // Table of Contents
  yPos = 140
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("Table of Contents", margin, yPos)
  yPos += 15

  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  data.content.sections.forEach((section, idx) => {
    doc.text(`${idx + 1}. ${section.name} (${section.marks} marks)`, margin + 10, yPos)
    yPos += 8
  })

  // Sections
  doc.addPage()
  yPos = margin
  addWatermark()

  data.content.sections.forEach((section, sectionIdx) => {
    checkNewPage(50)

    // Section header
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.setDrawColor(79, 70, 229)
    doc.setLineWidth(0.5)
    doc.line(margin, yPos + 2, pageWidth - margin, yPos + 2)
    yPos += 10
    doc.text(`${section.name}`, margin, yPos)
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.text(`(${section.marks} marks)`, pageWidth - margin - 30, yPos)
    yPos += 15

    // Questions
    section.questions.forEach((q, qIdx) => {
      checkNewPage(40)

      doc.setFontSize(11)
      doc.setFont("helvetica", "bold")
      const questionNum = `Q${sectionIdx + 1}.${qIdx + 1}.`
      doc.text(questionNum, margin, yPos)

      // Marks
      if (q.marks) {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(9)
        doc.text(`[${q.marks} marks]`, pageWidth - margin - 20, yPos)
      }

      // Question text
      doc.setFont("helvetica", "normal")
      doc.setFontSize(10)
      const questionLines = doc.splitTextToSize(q.text, pageWidth - 2 * margin - 40)
      yPos += 6
      doc.text(questionLines, margin + 15, yPos)
      yPos += questionLines.length * 5 + 5

      // Answer if included
      if (q.answer) {
        checkNewPage(20)
        doc.setFontSize(9)
        doc.setTextColor(34, 139, 34)
        doc.setFont("helvetica", "italic")
        const answerLines = doc.splitTextToSize(`Answer: ${q.answer}`, pageWidth - 2 * margin - 40)
        doc.text(answerLines, margin + 15, yPos)
        yPos += answerLines.length * 4 + 5
        doc.setTextColor(0, 0, 0)
      }

      yPos += 10
    })

    yPos += 10
  })

  // Formulas section
  if (data.content.formulas && data.content.formulas.length > 0) {
    checkNewPage(60)
    doc.addPage()
    yPos = margin
    addWatermark()

    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.setFillColor(255, 243, 224)
    doc.rect(margin - 5, yPos - 5, pageWidth - 2 * margin + 10, 15, "F")
    doc.text("Important Formulas", margin, yPos + 5)
    yPos += 25

    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    data.content.formulas.forEach((formula) => {
      checkNewPage(15)
      doc.text(`• ${formula}`, margin + 5, yPos)
      yPos += 8
    })
  }

  // Tips section
  if (data.content.tips && data.content.tips.length > 0) {
    checkNewPage(60)

    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.setFillColor(227, 242, 253)
    doc.rect(margin - 5, yPos - 5, pageWidth - 2 * margin + 10, 15, "F")
    doc.text("Exam Tips", margin, yPos + 5)
    yPos += 25

    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    data.content.tips.forEach((tip) => {
      checkNewPage(15)
      const tipLines = doc.splitTextToSize(`• ${tip}`, pageWidth - 2 * margin - 10)
      doc.text(tipLines, margin + 5, yPos)
      yPos += tipLines.length * 5 + 3
    })
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    )
    doc.text(
      "ExamEase - Smart Study & Exam Companion",
      pageWidth - margin,
      pageHeight - 10,
      { align: "right" }
    )
  }

  return doc
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename)
}

export function previewPDF(doc: jsPDF): string {
  return doc.output("dataurlstring")
}
